Explicitly require Python 3.4.
Fixes:

    NameError: global name 'BrokenPipeError' is not defined

and:

    AttributeError: 'module' object has no attribute 'unescape'